apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-service
spec:
  type: NodePort
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 80
  - name: api-ssl
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: {{ .Release.Name }}-deploy
